server {
  # 监听 80 端口，处理 IPv4 请求，http 请求默认是 80 端口
  listen 80;

  # 监听 80 端口，处理 IPv6 请求
  listen [::]:80;

  # 默认接收所有域名/主机名的请求
  server_name _;

  # 定义前端打包后的静态文件目录
  # 例如 index.html、js、css、assets 等文件都放这里
  root /usr/share/nginx/html;

  # 默认前端首页文件
  index index.html;

  # 处理前端页面请求
  location / {

    # 先尝试查找真实文件
    # 再尝试查找真实目录
    # 如果都找不到，则返回 index.html
    #
    # 主要用于支持 Vue Router / React Router 的 history 模式
    # 例如直接访问 /user/detail 时不会出现 404
    try_files $uri $uri/ /index.html;
  }

  # 健康检查接口
  # 访问 /healthz 时直接返回 HTTP 200 和 "ok"
  # 常用于 Docker、K8s、负载均衡器判断服务是否正常
  location = /healthz {

    # 健康检查请求不记录访问日志
    access_log off;

    # 返回内容类型为纯文本
    add_header Content-Type text/plain;

    # 直接返回 200 状态码和 ok
    return 200 "ok\n";
  }
}